### ISSUE TITLE
Two Vimeo specs fail

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#101]
I noticed this while I handled #100 

`Vimeo#available?` returns `true` with videos that don't exist and videos that are password protected.

I'll take a look at this when I look at #95 

```ruby
  1) VideoInfo::Providers::Vimeo#available? with 'this video does not exist' video #available? should not be available
     Failure/Error: it { is_expected.to_not be_available }
       expected `#<VideoInfo:0x0000000340b430 @provider=#<VideoInfo::Providers::Vimeo:0x0000000340ac38 @options={"User-Agent"=>"VideoInfo/2.5.0", "Authorization"=>"bearer 6b66b015a3504793b4f541d878f46ff6", "Accept"=>"application/vnd.vimeo.*+json;version=3.2"}, @url="http://vimeo.com/59312311", @video_id="59312311">>.available?` to return false, got true
     # ./spec/lib/video_info/providers/vimeo_spec.rb:60:in `block (5 levels) in <top (required)>'

  2) VideoInfo::Providers::Vimeo#available? with 'password required' video #available? should not be available
     Failure/Error: it { is_expected.to_not be_available }
       expected `#<VideoInfo:0x000000035848c0 @provider=#<VideoInfo::Providers::Vimeo:0x00000003584190 @options={"User-Agent"=>"VideoInfo/2.5.0", "Authorization"=>"bearer 6b66b015a3504793b4f541d878f46ff6", "Accept"=>"application/vnd.vimeo.*+json;version=3.2"}, @url="http://vimeo.com/74636562", @video_id="74636562">>.available?` to return false, got true
     # ./spec/lib/video_info/providers/vimeo_spec.rb:68:in `block (5 levels) in <top (required)>'
```

**Comment by vheuken** [comment]
I fixed this in commit a6e11c4a89022fd0e78360979ac92a8f84b98efe by making `available?` return false when the response code is 400. This doesn't seem to break any of the other specs, but I'm not sure if this is the best solution. I might have to take a deeper look at how the API requests for Vimeo are handled. 

For now, I'll mark this as fixed. I'll make a note in #95 to check this out.
